spring:
  datasource:
    url: jdbc:mysql://bit-hive.cx4c86coqxvs.ap-northeast-2.rds.amazonaws.com:3306/bithive
    username: admin
    password: ng9skpE3vAGLnKea0Fd5
# 뉴스 API KEY
my:
  api:
    deepsearch-key: 56dcc8e767f84a708c04e6589d943371